/*High level action creators*/
export const SAVE_CV = "SAVE_CV";
export const UPDATE_CV = "SAVE_CV";
export const FETCH_CV = "FETCH_CV";

/* UTILITY ACTION CREATORS */
export const FETCH_ALL_COUNTRIES = 'FETCH_ALL_COUNTRIES';
export const FETCH_ALL_GENDERS = 'FETCH_ALL_GENDERS';
export const FETCH_ALL_SELF_ASSESSMENT_PROPERTIES = 'FETCH_ALL_SELF_ASSESSMENT_PROPERTIES';
export const FETCH_ALL_LANGUAGE_SELF_ASSESSMENT_PROPERTIES = 'FETCH_ALL_LANGUAGE_SELF_ASSESSMENT_PROPERTIES';
export const FETCH_ALL_TITLE_PROPERTIES = 'FETCH_ALL_TITLE_PROPERTIES';
export const FETCH_ALL_COMPANY_SIZES = 'FETCH_ALL_COMPANY_SIZES';
export const FETCH_ALL_CV_JOB_MODES = 'FETCH_ALL_CV_JOB_MODES';
export const FETCH_ALL_CV_CAREER_LEVELS = 'FETCH_ALL_CV_CAREER_LEVELS';
export const FETCH_ALL_EDU_DEGREES = 'FETCH_ALL_EDU_DEGREES';
export const FETCH_ALL_OTHER_CV_INFO_TYPES = 'FETCH_ALL_OTHER_CV_INFO_TYPES';

