/*High level action creators*/
export const SAVE_CV = "SAVE_CV";
export const UPDATE_CV = "SAVE_CV";
export const FETCH_CV = "FETCH_CV";

/* Form level action creators */
export const FETCH_ABOUT_CV ='FETCH_ABOUT_CV';
export const FETCH_ABOUT_PERSON ='FETCH_ABOUT_PERSON';
export const FETCH_WORK_HISTORY ='FETCH_WORK_HISTORY';
export const FETCH_TARGET ='FETCH_TARGET';
export const FETCH_EDUCATION ='FETCH_EDUCATION';
export const FETCH_COURSES ='FETCH_COURSES';
export const FETCH_REFERENCES ='FETCH_REFERENCES';
export const FETCH_SKILLS ='FETCH_SKILLS';
export const FETCH_OTHER_INFO ='FETCH_OTHER_INFO';

/* UTILITY ACTION CREATORS */
export const FETCH_ALL_COUNTRIES = 'FETCH_ALL_COUNTRIES';
export const FETCH_ALL_GENDERS = 'FETCH_ALL_GENDERS';
export const FETCH_ALL_SELF_ASSESSMENT_PROPERTIES = 'FETCH_ALL_SELF_ASSESSMENT_PROPERTIES';
export const FETCH_ALL_LANGUAGE_SELF_ASSESSMENT_PROPERTIES = 'FETCH_ALL_LANGUAGE_SELF_ASSESSMENT_PROPERTIES';
export const FETCH_ALL_TITLE_PROPERTIES = 'FETCH_ALL_TITLE_PROPERTIES';
export const FETCH_ALL_COMPANY_SIZES = 'FETCH_ALL_COMPANY_SIZES';
export const FETCH_ALL_CV_JOB_MODES = 'FETCH_ALL_CV_JOB_MODES';
export const FETCH_ALL_CV_CAREER_LEVELS = 'FETCH_ALL_CV_CAREER_LEVELS';
export const FETCH_ALL_EDU_DEGREES = 'FETCH_ALL_EDU_DEGREES';
export const FETCH_ALL_OTHER_CV_INFO_TYPES = 'FETCH_ALL_OTHER_CV_INFO_TYPES';

/* OTHER INFO ACTION CREATORS */
export const CREATE_OTHER_INFO = 'CREATE_OTHER_INFO';
export const UPDATE_OTHER_INFO = 'CREATE_OTHER_INFO';
export const REMOVE_OTHER_INFO = 'REMOVE_OTHER_INFO';

/* REFERENCE ACTION CREATORS */
export const CREATE_REFERENCE = 'CREATE_REFERENCE';
export const UPDATE_REFERENCE = 'UPDATE_REFERENCE';
export const REMOVE_REFERENCE = 'REMOVE_REFERENCE';

/* SKILL ACTION CREATORS */
export const CREATE_SKILL = 'CREATE_SKILL';
export const UPDATE_SKILL = 'UPDATE_SKILL';
export const REMOVE_SKILL = 'REMOVE_SKILL';

/* EDUCATION ACTION CREATORS */
export const CREATE_EDUCATION = 'CREATE_EDUCATION';
export const UPDATE_EDUCATION = 'UPDATE_EDUCATION';
export const REMOVE_EDUCATION = 'REMOVE_EDUCATION';

/* COURSES ACTION CREATORS */
export const CREATE_COURSE = 'CREATE_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const REMOVE_COURSE = 'REMOVE_COURSE';

/* WORKHISTORY ACTION CREATORS */
export const CREATE_WORK_HISTORY = 'CREATE_WORK_HISTORY';
export const UPDATE_WORK_HISTORY = 'UPDATE_WORK_HISTORY';
export const REMOVE_WORK_HISTORY = 'REMOVE_WORK_HISTORY';